# Start: Enable SSL on localhost
server:
  ssl:
    key-store: ${server.ssl.keystore} #classpath:dev.localhost.com.p12
    key-store-password: ${server.ssl.password}
    key-store-type: PKCS12

    key-password: ${server.ssl.password}

    # trust-store: ${server.ssl.keystore} #classpath:dev.localhost.com.p12
    # trust-store-password: ${server.ssl.password}
    # trust-store-type: PKCS12
# End: Enable SSL on localhost
